# Generated by Django 6.0.7 on 2026-07-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediApp', '0002_category_batch_purchase_price_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='Mark as permanent/loyal member to receive stock availability notifications.'),
        ),
    ]
