# Generated by Django 6.0.7 on 2026-07-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediApp', '0003_add_is_permanent_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this if the medicine is discontinued or no longer available'),
        ),
    ]
