# Generated by Django 5.2.17 on 2026-08-25 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediApp', '0006_invoice_purchaseorder_medicine_preferred_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('medicine_name', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('reminder_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
