# Generated by Django 5.2.17 on 2026-08-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediApp', '0007_expiryreminderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Set to True after sending expiry reminders for this batch'),
        ),
    ]
