# Generated by Django 6.1 on 2026-09-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediApp', '0009_purchasebillimport_wantbookitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebillimport',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_imports', to='MediApp.purchaseorder'),
        ),
    ]
