# Generated by Django 6.1 on 2026-09-12 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediApp', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expiryreminderlog',
            name='customer_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='expiryreminderlog',
            name='expiry_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expiryreminderlog',
            name='medicine_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='expiryreminderlog',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Refunded', 'Refunded')], db_index=True, default='Completed', max_length=20),
        ),
    ]
