# Generated by Django 5.2.17 on 2026-09-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediApp', '0012_alter_batch_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='rack_number',
            field=models.CharField(blank=True, help_text='Storage Rack or Cabinet, e.g., Rack A-1, Cabinet 3', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='shelf_number',
            field=models.CharField(blank=True, help_text='Shelf or Drawer Number, e.g., Shelf 2, Box B', max_length=50, null=True),
        ),
    ]
